name: lift
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.4.2
  flutter:
    sdk: flutter
  dio_smart_retry: ^5.0.0
  retrofit: 4.1.0
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  textfield_tags: ^3.0.1
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^8.2.5
  flutter_tags: ^1.0.0-nullsafety.1
  flutter_keychain: ^2.4.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: 7.0.7
  build_runner: 2.4.5
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - Server_URL.env

  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothicBold.ttf
        - asset: assets/fonts/NanumGothic.ttf
        - asset: assets/fonts/NanumGothicExtraBold.ttf
        - asset: assets/fonts/NanumGothicLight.ttf

