// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qRsIcXxqGbSaAZw1WXsRiWIEbiOPixc',
    appId: '1:586865475334:web:405616f523fff55dada887',
    messagingSenderId: '586865475334',
    projectId: 'lift-6417c',
    authDomain: 'lift-6417c.firebaseapp.com',
    storageBucket: 'lift-6417c.appspot.com',
    measurementId: 'G-STH71KL05C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVN7KXlFt9I_9gxwTDsPbriYk-ECcaB0',
    appId: '1:586865475334:android:9648109734d28d2bada887',
    messagingSenderId: '586865475334',
    projectId: 'lift-6417c',
    storageBucket: 'lift-6417c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVyfVwNAYNyQNKT00mS7CftDQ9jvemEhk',
    appId: '1:586865475334:ios:0c6af966349a5bcbada887',
    messagingSenderId: '586865475334',
    projectId: 'lift-6417c',
    storageBucket: 'lift-6417c.appspot.com',
    iosBundleId: 'com.kimgeonwoo.lift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVyfVwNAYNyQNKT00mS7CftDQ9jvemEhk',
    appId: '1:586865475334:ios:d8d2718c352dba90ada887',
    messagingSenderId: '586865475334',
    projectId: 'lift-6417c',
    storageBucket: 'lift-6417c.appspot.com',
    iosBundleId: 'com.example.lift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qRsIcXxqGbSaAZw1WXsRiWIEbiOPixc',
    appId: '1:586865475334:web:c3cf32d0e97a5e68ada887',
    messagingSenderId: '586865475334',
    projectId: 'lift-6417c',
    authDomain: 'lift-6417c.firebaseapp.com',
    storageBucket: 'lift-6417c.appspot.com',
    measurementId: 'G-YQLBXDG9J1',
  );
}
